version: '3.8'

services:
    # Backend (Laravel)
    backend:
        build:
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./PLS:/var/www/html
        networks:
            - app-network
        depends_on:
            - mysql
        environment:
            - APP_URL=http://localhost:8002
            - APP_ENV=local
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel_db
            - DB_USERNAME=admin
            - DB_PASSWORD=admin
        ports:
            - "8002:8000"

    # Frontend (React)
    frontend:
        build:
            dockerfile: Dockerfile.react
        container_name: react_app
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "3000:3000"
        networks:
            - app-network

    # Database (MySQL)
    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
           - MYSQL_DATABASE:laravel_db
           - MYSQL_USER:admin
           - MYSQL_PASSWORD:admin
           - MYSQL_ROOT_PASSWORD:root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
