// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using PLS.Api.Data;

#nullable disable

namespace PLS.Api.Migrations
{
    [DbContext(typeof(PlsDbContext))]
    [Migration("20260319101511_AddRequiresPasswordChange")]
    partial class AddRequiresPasswordChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PLS.Api.Models.Entities.Body", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyParts")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("body_parts");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int")
                        .HasColumnName("id_patient");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdPatient")
                        .IsUnique();

                    b.ToTable("bodies", (string)null);
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.OperationScene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("operation_scenes", (string)null);
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Atmung")
                        .HasColumnType("longtext")
                        .HasColumnName("atmung");

                    b.Property<string>("Blutung")
                        .HasColumnType("longtext")
                        .HasColumnName("blutung");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Dringend")
                        .HasColumnType("longtext")
                        .HasColumnName("dringend");

                    b.Property<string>("Kontaminiert")
                        .HasColumnType("longtext")
                        .HasColumnName("kontaminiert");

                    b.Property<double?>("LatitudePatient")
                        .HasColumnType("double")
                        .HasColumnName("latitude_patient");

                    b.Property<double?>("LongitudePatient")
                        .HasColumnType("double")
                        .HasColumnName("longitude_patient");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Radialispuls")
                        .HasColumnType("longtext")
                        .HasColumnName("radialispuls");

                    b.Property<string>("Transport")
                        .HasColumnType("longtext")
                        .HasColumnName("transport");

                    b.Property<string>("Triagefarbe")
                        .HasColumnType("longtext")
                        .HasColumnName("triagefarbe");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserIdUser")
                        .HasColumnType("int")
                        .HasColumnName("user_id_user");

                    b.HasKey("Id");

                    b.HasIndex("UserIdUser");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Point>("Position")
                        .HasColumnType("POINT")
                        .HasColumnName("position");

                    b.Property<string>("Triagefarbe")
                        .HasColumnType("longtext")
                        .HasColumnName("triagefarbe");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.QrCodeLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FirstLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_login");

                    b.Property<string>("QrLogin")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("qr_login");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("qr_code_logins", (string)null);
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.QrCodeLoginHasUser", b =>
                {
                    b.Property<int>("QrCodeLoginId")
                        .HasColumnType("int")
                        .HasColumnName("qr_code_login_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("QrCodeLoginId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("qr_code_login_has_users", (string)null);
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.QrCodePatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("OperationSceneId")
                        .HasColumnType("int")
                        .HasColumnName("operation_scene_id");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("QrLogin")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("qr_login");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OperationSceneId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("qr_code_patients", (string)null);
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdminRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("admin_role");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FirstLoginTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_login_time");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_time");

                    b.Property<double?>("LatitudeUser")
                        .HasColumnType("double")
                        .HasColumnName("latitude_user");

                    b.Property<double?>("LongitudeUser")
                        .HasColumnType("double")
                        .HasColumnName("longitude_user");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.Body", b =>
                {
                    b.HasOne("PLS.Api.Models.Entities.Patient", "Patient")
                        .WithOne("Body")
                        .HasForeignKey("PLS.Api.Models.Entities.Body", "IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.Patient", b =>
                {
                    b.HasOne("PLS.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.QrCodeLoginHasUser", b =>
                {
                    b.HasOne("PLS.Api.Models.Entities.QrCodeLogin", "QrCodeLogin")
                        .WithMany()
                        .HasForeignKey("QrCodeLoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PLS.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QrCodeLogin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.QrCodePatient", b =>
                {
                    b.HasOne("PLS.Api.Models.Entities.OperationScene", "OperationScene")
                        .WithMany()
                        .HasForeignKey("OperationSceneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PLS.Api.Models.Entities.Patient", "Patient")
                        .WithOne("QrCodePatient")
                        .HasForeignKey("PLS.Api.Models.Entities.QrCodePatient", "PatientId");

                    b.HasOne("PLS.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OperationScene");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PLS.Api.Models.Entities.Patient", b =>
                {
                    b.Navigation("Body");

                    b.Navigation("QrCodePatient");
                });
#pragma warning restore 612, 618
        }
    }
}
