version: '3.8'

services:
  # Laravel application
  laravel_app:
    image: pls-laravel_app:latest    # Dein bestehendes Laravel Image
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    expose:
      - "9000"  # PHP-FPM ist auf Port 9000 verfügbar
    depends_on:
      - mysql_db
    networks:
      - app_network

  # Nginx für HTTPS
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Deine angepasste nginx.conf
      - ./certs:/etc/nginx/certs  # Deine SSL-Zertifikate
    ports:
      - "80:80"   # HTTP Port
      - "443:443" # HTTPS Port
    depends_on:
      - laravel_app
    networks:
      - app_network

  # MySQL database
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
